#!/usr/bin/env bash
# Shared helpers for the Quansio V8.1 local development stack (GOV-007).
#
# Sourced by scripts/dev/{up,down,reset,seed,healthcheck}. Resolves the
# non-secret settings from config/dev.yaml (environment overrides win) and
# exposes the `compose` wrapper used by every command.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG="$ROOT/config/dev.yaml"
ENV_FILE="${QUANSIO_DEV_ENV_FILE:-$ROOT/.env}"

if command -v python3.12 >/dev/null 2>&1; then
  PYTHON="${PYTHON:-python3.12}"
else
  PYTHON="${PYTHON:-python3}"
fi

# Read a flat `key: value` entry from config/dev.yaml.
cfg() {
  sed -n -E "s/^[[:space:]]*$1:[[:space:]]*(.*)$/\1/p" "$CONFIG" | head -1
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "dev stack: docker CLI not found" >&2
    exit 2
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "dev stack: Docker daemon unavailable (BLOCKED_EXTERNAL)" >&2
    exit 2
  fi
}

# Non-secret settings. Environment overrides win over config/dev.yaml.
export QUANSIO_DEV_COMPOSE_PROJECT="${QUANSIO_DEV_COMPOSE_PROJECT:-$(cfg compose_project)}"
export QUANSIO_DEV_POSTGRES_IMAGE="${QUANSIO_DEV_POSTGRES_IMAGE:-$(cfg postgres_image)}"
export QUANSIO_DEV_POSTGRES_HOST="${QUANSIO_DEV_POSTGRES_HOST:-$(cfg postgres_host)}"
export QUANSIO_DEV_POSTGRES_PORT="${QUANSIO_DEV_POSTGRES_PORT:-$(cfg postgres_port)}"
export QUANSIO_DEV_POSTGRES_USER="${QUANSIO_DEV_POSTGRES_USER:-$(cfg postgres_user)}"
export QUANSIO_DEV_POSTGRES_DB="${QUANSIO_DEV_POSTGRES_DB:-$(cfg postgres_db)}"
export QUANSIO_DEV_NATS_IMAGE="${QUANSIO_DEV_NATS_IMAGE:-$(cfg nats_image)}"
export QUANSIO_DEV_NATS_HOST="${QUANSIO_DEV_NATS_HOST:-$(cfg nats_host)}"
export QUANSIO_DEV_NATS_PORT="${QUANSIO_DEV_NATS_PORT:-$(cfg nats_port)}"
export QUANSIO_DEV_NATS_MONITOR_PORT="${QUANSIO_DEV_NATS_MONITOR_PORT:-$(cfg nats_monitor_port)}"
export QUANSIO_DEV_MINIO_IMAGE="${QUANSIO_DEV_MINIO_IMAGE:-$(cfg minio_image)}"
export QUANSIO_DEV_MINIO_MC_IMAGE="${QUANSIO_DEV_MINIO_MC_IMAGE:-$(cfg minio_mc_image)}"
export QUANSIO_DEV_MINIO_HOST="${QUANSIO_DEV_MINIO_HOST:-$(cfg minio_host)}"
export QUANSIO_DEV_MINIO_PORT="${QUANSIO_DEV_MINIO_PORT:-$(cfg minio_port)}"
export QUANSIO_DEV_MINIO_CONSOLE_PORT="${QUANSIO_DEV_MINIO_CONSOLE_PORT:-$(cfg minio_console_port)}"
export QUANSIO_DEV_MINIO_BUCKET="${QUANSIO_DEV_MINIO_BUCKET:-$(cfg minio_bucket)}"
export QUANSIO_DEV_MINIO_ROOT_USER="${QUANSIO_DEV_MINIO_ROOT_USER:-$(cfg minio_root_user)}"
export QUANSIO_DEV_STUB_PROVIDER_IMAGE="${QUANSIO_DEV_STUB_PROVIDER_IMAGE:-$(cfg stub_provider_image)}"
export QUANSIO_DEV_STUB_PROVIDER_HOST="${QUANSIO_DEV_STUB_PROVIDER_HOST:-$(cfg stub_provider_host)}"
export QUANSIO_DEV_STUB_PROVIDER_PORT="${QUANSIO_DEV_STUB_PROVIDER_PORT:-$(cfg stub_provider_port)}"
export QUANSIO_DEV_VECTOR_ADAPTER_IMAGE="${QUANSIO_DEV_VECTOR_ADAPTER_IMAGE:-$(cfg vector_adapter_image)}"
export QUANSIO_DEV_VECTOR_ADAPTER_PORT="${QUANSIO_DEV_VECTOR_ADAPTER_PORT:-$(cfg vector_adapter_port)}"
export QUANSIO_DEV_HEALTH_TIMEOUT="${QUANSIO_DEV_HEALTH_TIMEOUT:-$(cfg health_timeout_seconds)}"

# Dev-only credentials. Override by exporting these before `scripts/dev/up`;
# they are never production secrets and never live in config/ or the repo.
export QUANSIO_DEV_POSTGRES_PASSWORD="${QUANSIO_DEV_POSTGRES_PASSWORD:-quansio-dev-only}"
export QUANSIO_DEV_MINIO_ROOT_PASSWORD="${QUANSIO_DEV_MINIO_ROOT_PASSWORD:-quansio-dev-only}"

# All settings written to the generated, gitignored .env.
DEV_ENV_KEYS=(
  QUANSIO_DEV_COMPOSE_PROJECT
  QUANSIO_DEV_POSTGRES_IMAGE QUANSIO_DEV_POSTGRES_HOST QUANSIO_DEV_POSTGRES_PORT
  QUANSIO_DEV_POSTGRES_USER QUANSIO_DEV_POSTGRES_PASSWORD QUANSIO_DEV_POSTGRES_DB
  QUANSIO_DEV_NATS_IMAGE QUANSIO_DEV_NATS_HOST QUANSIO_DEV_NATS_PORT QUANSIO_DEV_NATS_MONITOR_PORT
  QUANSIO_DEV_MINIO_IMAGE QUANSIO_DEV_MINIO_MC_IMAGE QUANSIO_DEV_MINIO_HOST
  QUANSIO_DEV_MINIO_PORT QUANSIO_DEV_MINIO_CONSOLE_PORT QUANSIO_DEV_MINIO_BUCKET
  QUANSIO_DEV_MINIO_ROOT_USER QUANSIO_DEV_MINIO_ROOT_PASSWORD
  QUANSIO_DEV_STUB_PROVIDER_IMAGE QUANSIO_DEV_STUB_PROVIDER_HOST QUANSIO_DEV_STUB_PROVIDER_PORT
  QUANSIO_DEV_VECTOR_ADAPTER_IMAGE QUANSIO_DEV_VECTOR_ADAPTER_PORT
  QUANSIO_DEV_HEALTH_TIMEOUT
)

compose() {
  local opts=(-f "$ROOT/infra/compose/compose.yaml" --project-name "$QUANSIO_DEV_COMPOSE_PROJECT")
  if [[ -f "$ENV_FILE" ]]; then
    opts+=(--env-file "$ENV_FILE")
  fi
  docker compose "${opts[@]}" "$@"
}

# Create the gitignored .env once; never overwrite an existing one so an
# existing database volume keeps matching credentials. Idempotent.
write_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    return 0
  fi
  umask 077
  {
    echo "# Generated by scripts/dev/up from config/dev.yaml. Do not commit."
    echo "# Dev-only defaults for local development; never real secrets."
    for name in "${DEV_ENV_KEYS[@]}"; do
      printf '%s=%s\n' "$name" "${!name}"
    done
  } > "$ENV_FILE"
}

# --- readiness probes -------------------------------------------------------

check_postgres() {
  compose exec -T postgres pg_isready -U "$QUANSIO_DEV_POSTGRES_USER" -d "$QUANSIO_DEV_POSTGRES_DB" \
    >/dev/null 2>&1 || return 1
  local count
  count="$(compose exec -T postgres psql -tAq -U "$QUANSIO_DEV_POSTGRES_USER" -d "$QUANSIO_DEV_POSTGRES_DB" \
    -c "SELECT count(*) FROM pg_extension WHERE extname = 'vector'" 2>/dev/null | tr -d '[:space:]')"
  [[ "$count" == "1" ]]
}

check_nats() {
  "$PYTHON" - "$QUANSIO_DEV_NATS_HOST" "$QUANSIO_DEV_NATS_MONITOR_PORT" <<'PY'
import json, sys, urllib.request
base = f"http://{sys.argv[1]}:{sys.argv[2]}"
try:
    with urllib.request.urlopen(base + "/healthz", timeout=3) as response:
        assert response.status == 200
    with urllib.request.urlopen(base + "/jsz", timeout=3) as response:
        assert response.status == 200
        status = json.load(response)
    assert isinstance(status.get("config"), dict), "JetStream is not enabled"
except Exception as exc:  # noqa: BLE001 - any failure means not ready
    print(f"nats not ready: {exc}", file=sys.stderr)
    sys.exit(1)
PY
}

check_minio() {
  "$PYTHON" - "$QUANSIO_DEV_MINIO_HOST" "$QUANSIO_DEV_MINIO_PORT" <<'PY'
import sys, urllib.request
base = f"http://{sys.argv[1]}:{sys.argv[2]}"
try:
    with urllib.request.urlopen(base + "/minio/health/ready", timeout=3) as response:
        assert response.status == 200
except Exception as exc:  # noqa: BLE001 - any failure means not ready
    print(f"minio not ready: {exc}", file=sys.stderr)
    sys.exit(1)
PY
}
